### PR TITLE
Add yandex money card

### PR DESCRIPTION
**Pull request by Luchanso**
Example color:

image

### CODE REVIEW

**Comment by ai** [comment]
Tests were fallen because you forget to add your JSON to `index.js`.

**Comment by ai** [comment]
Also `localTitle` should be in Russian? ;)

**Comment by Luchanso** [comment]
@ai thanks :smiley:

**Comment by ai** [comment]
I think officiial title is `Яндекс.Деньги` with a dot ;)

**Comment by Luchanso** [comment]
@ai yeah, its better :smile_cat:

**Pull request merged**
