### PR TITLE
Add new Rocketbank BIN

### LINKED ISSUE #29: Add new Rocketbank
New Rockebank card uses different backend bank, so we need to add new BIN: `5321 30`

### PR DESCRIPTION
**Pull request by ai**
Close #29

### CODE REVIEW

**Comment by ramoona** [comment]
@ai looks like someone forgot to add  `require('./banks/rocketbank')` to index.js :)

**Comment by ai** [comment]
:D You are right. Good that we have linter :).

**Comment by ai** [comment]
Wait a second

**Comment by ai** [comment]
Done

**Pull request merged**
