### PR TITLE
Added all BY banks

### PR DESCRIPTION
**Pull request by altmind**
Also fixed npm test for node 0.12:
require('.') -> require ('./index')
node lint.js -> node --harmony lint.js

As I cannot put my hands on BINs of couple of banks(i will add them soon), i relaxed restriction on >0 prefixes for bank.

### CODE REVIEW

**Comment by ai** [comment]
Can you split this PR to 2 separated?

For node.js 0.12 and with banks.

Also it is bad to have `merge` commits.

**Comment by ai** [comment]
What do you change in `schema.json`?

**Comment by altmind** [comment]
>What do you change in schema.json?

Its because i've added 3 banks i dont know BINS yet. So i relaxed the limitation that at least 1 bin should be present

**Comment by altmind** [comment]
Lets please not split this in 2 PRs. I cannot run lint & test with current setup so i cannot do pre-commt checks as defined in CONTRIBUTION.md.

**Comment by ai** [comment]
Yeap. At least remove `merge` commit.

**Comment by ai** [comment]
You can find that BY banks BINs by http://bins.pro/search?action=searchbins&bins=&bank=&country=BY

**Comment by ai** [comment]
If this banks has no BINs in public databases, maybe we should not add them.

**Comment by altmind** [comment]
I think we should add banks that are public and issue cards. Its just cards we dont have info YET

**Comment by ai** [comment]
I afraid that nobody will update it and they will take a file size in web bundle without a reason

**Comment by altmind** [comment]
@Ramoona what's your opinion?

**Comment by Ramoona** [comment]
@altmind banks without BINs are useless and they'll probably become abandoned in future

**Comment by Ramoona** [comment]
Thanks for contribution. Can you please sent PR only with banks that have BINs? Also can you sent separated PR for test changes - good PR contains only 1 commit with only 1 change.

**Pull request closed without merging**
